const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: ["breakfast", "pancakes"],
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: ["lunch", "american"],
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: ["shakes", "buddy"],
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: ["breakfast", "american"],
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: ["lunch", "american"],
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: ["shakes", "buddy"],
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: ["breakfast", "american"],
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: ["lunch", "american"],
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: ["shakes", "buddy"],
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: "bison steak",
    category: ["dinner", "steak"],
    price: 22.99,
    img: "./images/item-10.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: "classic burger",
    category: ["lunch", "american"],
    price: 11.99,
    img: "./images/item-11.jpg",
    desc: `Salvia esse nihil, flexitarian Truffaut synth art party deep v chillwave.`,
  },
  {
    id: 12,
    title: "veggie delight",
    category: ["lunch", "american"],
    price: 14.99,
    img: "./images/item-12.jpg",
    desc: `Shoreditch edison bulb etsy chillwave shaman lumbersexual keffiyeh listicle vinyl. `,
  },
  {
    id: 13,
    title: "hawaiian paradise",
    category: ["dinner", "steak"],
    price: 19.99,
    img: "./images/item-13.jpg",
    desc: `Kale chips celiac brunch paleo semiotics tofu.`,
  },
  {
    id: 14,
    title: "veggie lover",
    category: ["dinner", "steak"],
    price: 17.99,
    img: "./images/item-14.jpg",
    desc: `Poke slow-carb man braid prism, vinyl subway tile before they sold out offal woke.`,
  },
  {
    id: 15,
    title: "steakhouse supreme",
    category: ["dinner", "steak"],
    price: 25.99,
    img: "./images/item-15.jpg",
    desc: `Cold-pressed heirloom poke, irony butcher plaid ramps knausgaard glossier cronut.`,
  },
  {
    id: 16,
    title: "salmon sensation",
    category: ["dinner", "steak"],
    price: 23.99,
    img: "./images/item-16.jpg",
    desc: `Sriracha unicorn ramps, vape hammock activated charcoal tumeric chartreuse knausgaard lyft ethical.`,
  },
];

module.exports = menu;
